# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'Microsoft Azure Sponsorship (0b85fa5b-f7d4-49de-8a4e-3fe85234f9c5)'
    appType: 'functionApp'
    appName: 'YAML.app'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
